# Generated by Django 5.0.6 on 2024-06-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
