# Generated by Django 5.0.6 on 2024-06-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_owner_id_car_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
